AWSTemplateFormatVersion: "2010-09-09"
Description: CloudFormation template for currency exchange tracking application

Resources:
  ApiEndpointFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ./api_endpoint # Path to the directory containing API endpoint function code
      Handler: api_endpoint.endpoint_handler
      Runtime: python3.11 # Use Python 3.11 runtime
      Policies:
        - AWSLambdaBasicExecutionRole # Basic IAM role for Lambda function

  DailyFetchFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ./daily_fetch # Path to the directory containing daily fetch function code
      Handler: daily_fetch.fetch_handler
      Runtime: python3.11 # Use Python 3.11 runtime
      Policies:
        - AWSLambdaBasicExecutionRole # Basic IAM role for Lambda function

  # You can define other AWS resources required for your application here, such as DynamoDB, API Gateway, etc.
  # ...

Outputs:
  ApiEndpointFunctionArn:
    Value: !GetAtt ApiEndpointFunction.Arn

  DailyFetchFunctionArn:
    Value: !GetAtt DailyFetchFunction.Arn
